/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cactus
 */
public class FormUsuarioBDos extends javax.swing.JFrame {

    /**
     * Creates new form FormUsuarioBDos
     */
    public FormUsuarioBDos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/logoNewSolutionLogin.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboIngresoFamiliarPromedio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtGananciaMinimaMensual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboActualmenteDedica = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboPrincipalMotivacionPostu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboIngresosIndependiente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboSubsidioFamiliarEmergencia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboSubsidioMinimoGarantizado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboAyudasSociales = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboPrestamosCreditos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtOtraRelevante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaActividadPrincipalProyecto = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaTiempoOtorgaraProyecto = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboIngresosMedianteProyecto = new javax.swing.JComboBox<>();
        cboActividadesPrincipalesProyecto = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaFormaPromocionarVender = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaProcesoElaboracion = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaExperienciaCapacitacion = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        cboParticipadoPrograma = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaAportesPropios = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        cboIdentidadCultural = new javax.swing.JComboBox<>();
        txtIdentidadCultural = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtFinanMontoConadi = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaFinanDetalleProducto = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtFinanMontoConadi2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txaFinanDetalleProducto2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("¿Actualmente cuál es su ingreso familiar promedio?");

        cboIngresoFamiliarPromedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Sin ingresos.", "Menor al IMM ($350.000)", "Hasta el IMM ($350.000)", "Mayor al IMM ($350.000)" }));
        cboIngresoFamiliarPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIngresoFamiliarPromedioActionPerformed(evt);
            }
        });

        jLabel3.setText("¿Cuál es la ganancia mínima mensual que espera obtener del proyecto?");

        txtGananciaMinimaMensual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGananciaMinimaMensualKeyTyped(evt);
            }
        });

        jLabel4.setText("¿Actualmente a que se dedica?");

        cboActualmenteDedica.setEditable(true);
        cboActualmenteDedica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Labores domésticas", "Inactivo por razones de salud", "Cuidado de familiar", "Jubilado/a", "Estudia." }));

        jLabel5.setText("¿Cuál es la principal motivación de la presente postulación? ");

        cboPrincipalMotivacionPostu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Obtener ingresos suficientes para necesidades básicas.", "No ha logrado encontrar trabajo como asalariado/a.", "Fue despedido/a de un empleo asalariado.", "Deseaba iniciar su proyecto o trabajo independiente.", "<html>Para tener mayor flexibilidad (horarios,<p> lugar de trabajo) y atender al mismo tiempo<p>las responsabilidades familiares.</html>", "Porque encontró una oportunidad de mercado."}));

        jLabel6.setText("Ha logrado generar ingresos de forma independiente");

        cboIngresosIndependiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Si", "No", "No sabe" }));

        jLabel7.setText("<html>ha logrado acceder al subsidio de ingreso familiar<p>de emergencia del Ministerio de Desarrollo<p>Social y Familia</html>");

        cboSubsidioFamiliarEmergencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Si", "No", "No sabe" }));

        jLabel8.setText("<html>ha logrado acceder al subsidio de Ingreso mínimo<p>garantizado del Ministerio de Desarrollo Social<p>y Familia</html>");

        cboSubsidioMinimoGarantizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Si", "No", "No sabe" }));

        jLabel9.setText("<html>ha recibido ayudas sociales (alimentos u otros<p>productos de subsistencia). De parte de instituciones<p>públicas o privadas</html>");

        cboAyudasSociales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Si", "No", "No sabe" }));

        jLabel10.setText("ha logrado acceder a préstamos y/o créditos de instituciones financieras");

        cboPrestamosCreditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Si", "No", "No sabe" }));

        jLabel11.setText("Otra que considere relevante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cboIngresoFamiliarPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtGananciaMinimaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboActualmenteDedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboPrincipalMotivacionPostu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cboIngresosIndependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cboSubsidioFamiliarEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cboSubsidioMinimoGarantizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cboAyudasSociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboPrestamosCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtOtraRelevante, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboIngresoFamiliarPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGananciaMinimaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboActualmenteDedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPrincipalMotivacionPostu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboIngresosIndependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSubsidioFamiliarEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSubsidioMinimoGarantizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAyudasSociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPrestamosCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOtraRelevante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("INFORMACIÓN REQUERIDA PARA EL PROGRAMA");

        jLabel13.setText("Nombre del proyecto");

        jLabel14.setText("¿Cuál es la actividad principal del proyecto?");

        txaActividadPrincipalProyecto.setColumns(20);
        txaActividadPrincipalProyecto.setRows(5);
        jScrollPane1.setViewportView(txaActividadPrincipalProyecto);

        jLabel15.setText("¿Cuál es la dedicación de tiempo que le otorgará al proyecto para su ejecución? ");

        txaTiempoOtorgaraProyecto.setColumns(20);
        txaTiempoOtorgaraProyecto.setRows(5);
        jScrollPane2.setViewportView(txaTiempoOtorgaraProyecto);

        jLabel16.setText("<html>¿Cuál es la periodicidad con la que espera<p>generar ingresos mediante el proyecto?</html>");

        jLabel17.setText("<html>¿Donde llevará a cabo las actividades principales<p>del proyecto de microemprendimiento?</html>");

        cboIngresosMedianteProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Diario", "Mensual", "anual", "Semanal", "trimestral", "Quincenal", "semestral" }));

        cboActividadesPrincipalesProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Dentro de la vivienda en lugares improvisados.", "<html>Dentro de la vivienda con una<p>instalación especial para el proyecto.</html>", "<html>En instalaciones fuera de la vivienda (fábrica, taller,<p>local, tienda u otro espacio de comercialización autorizado).</html>", "En un predio agrícola.", "En vivienda o negocio de los potenciales clientes." }));

        jLabel18.setText("<html>Describa la forma de promocionar y vender sus<p>productos o servicios, si utiliza internet y a<p>quienes considera como clientes.</html>");

        txaFormaPromocionarVender.setColumns(20);
        txaFormaPromocionarVender.setRows(5);
        jScrollPane3.setViewportView(txaFormaPromocionarVender);

        jLabel19.setText("<html>¿Conoce el proceso de elaboración del producto<p>o servicio a entregar? Describa los pasos para obtener<p> el producto terminado o servicio a entregar.</html>");

        txaProcesoElaboracion.setColumns(20);
        txaProcesoElaboracion.setRows(5);
        jScrollPane4.setViewportView(txaProcesoElaboracion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(cboIngresosMedianteProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboActividadesPrincipalesProyecto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboIngresosMedianteProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboActividadesPrincipalesProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("INFORMACION DEL PROYECTO");

        jLabel20.setText("<html>¿Ha tenido experiencia y/o capacitación en ámbitos<p>relacionados al presente proyecto?</html>");

        txaExperienciaCapacitacion.setColumns(20);
        txaExperienciaCapacitacion.setRows(5);
        jScrollPane5.setViewportView(txaExperienciaCapacitacion);

        jLabel21.setText("¿Ha participado del Programa en versiones anteriores?");

        cboParticipadoPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "No ha participado.", "ha participado hasta 3 veces.", "ha participado solo 1 vez.", "ha participado más de 3 veces." }));

        jLabel22.setText("¿Considera aportes propios al proyecto? opcional.");

        txaAportesPropios.setColumns(20);
        txaAportesPropios.setRows(5);
        jScrollPane6.setViewportView(txaAportesPropios);

        jLabel23.setText("<html>¿Cuál es la pertinencia o Identidad cultural de<p>los pueblos indígenas que se ve reflejada<p> en el proyecto?</html>");

        cboIdentidadCultural.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-","<html>El proceso de producción, incluye conocimiento<p>ancestral, técnicas específicas y propias de los<p>pueblos indígenas (Conocimientos tradicionales traspasados<p> de generación en generación).</html>", "<html>Preparaciones a base de alimentos o materia prima<p>tradicionales de los pueblos indígenas.</html>", "<html>El producto terminado o la prestación servicio<p>difunde alguna expresión artística y/o cultural mediante<p>la utilización de simbología y diseño que fomente<p>la identidad cultural material e inmaterial de los pueblos<p>indígenas</html>", "Otro"}));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(cboParticipadoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(cboIdentidadCultural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdentidadCultural, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboParticipadoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboIdentidadCultural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentidadCultural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setText("Bienes de Capital (equipos, maquinas, herramientas, implementos).");

        jLabel26.setText("Monto solicitado a CONADI");

        txtFinanMontoConadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFinanMontoConadiKeyTyped(evt);
            }
        });

        jLabel27.setText("Detalle de productos");

        txaFinanDetalleProducto.setColumns(20);
        txaFinanDetalleProducto.setRows(5);
        jScrollPane7.setViewportView(txaFinanDetalleProducto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFinanMontoConadi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtFinanMontoConadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Financiamiento y costos del proyecto");

        jLabel28.setText("Materias primas o insumos");

        jLabel29.setText("Monto solicitado a CONADI");

        txtFinanMontoConadi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFinanMontoConadi2KeyTyped(evt);
            }
        });

        jLabel30.setText("Detalle de productos");

        txaFinanDetalleProducto2.setColumns(20);
        txaFinanDetalleProducto2.setRows(5);
        jScrollPane8.setViewportView(txaFinanDetalleProducto2);

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFinanMontoConadi2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtFinanMontoConadi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboIngresoFamiliarPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIngresoFamiliarPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboIngresoFamiliarPromedioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(cboIngresoFamiliarPromedio.getSelectedItem() == "-Seleccione-"){
            
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un INGRESO FAMILIAR PROMEDIO valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboActualmenteDedica.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar a que se DEDICA ACTUAMLMENTE valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboPrincipalMotivacionPostu.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar una PRINCIPAL MOTIVACION DE LA POSTULACION valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboIngresosIndependiente.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un INGRESO INDEPENDIENTE valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboSubsidioFamiliarEmergencia.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un SUBSIDIO FAMILIAR DE EMERGENCIA valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboSubsidioMinimoGarantizado.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un SUBSIDIO MINIMO GARANTIZADO valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboAyudasSociales.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar AYUDAS SOCIALES valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboPrestamosCreditos.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar PRESTAMO O CREDITO valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboIngresosMedianteProyecto.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar INGRESOS MEDIANTE PROYECTO valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboActividadesPrincipalesProyecto.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar ACTIVIDADES PRINCIPALES DEL PROYECTO valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboParticipadoPrograma.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar si a PARTICIPADO EN PROGRAMAS valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboIdentidadCultural.getSelectedItem() == "-Seleccione-"){
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar una IDENTIDAD CULTURAL valido", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(txtGananciaMinimaMensual.getText().trim().isEmpty() || txtNombreProyecto.getText().trim().isEmpty() 
                || txaActividadPrincipalProyecto.getText().trim().isEmpty() || txaTiempoOtorgaraProyecto.getText().trim().isEmpty() 
                || txaFormaPromocionarVender.getText().trim().isEmpty() || txaProcesoElaboracion.getText().trim().isEmpty() 
                || txaExperienciaCapacitacion.getText().trim().isEmpty() || txaAportesPropios.getText().trim().isEmpty() 
                || txtFinanMontoConadi.getText().trim().isEmpty() || txaFinanDetalleProducto.getText().trim().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos de\n INFORMACIÓN REQUERIDA PARA EL PROGRAMA\ny INFORMACION DEL PROYECTO", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else if(cboIdentidadCultural.getSelectedItem() == "Otro"){
            
            if(txtIdentidadCultural.getText().trim().isEmpty()){
                
                JOptionPane.showMessageDialog(null, "Debe completar el campo para OTROS", "ERROR", JOptionPane.WARNING_MESSAGE);
                
            }
        }else{
            
            
            
            FormUsuarioBTres abrir = new FormUsuarioBTres();
            abrir.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtGananciaMinimaMensualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGananciaMinimaMensualKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtGananciaMinimaMensualKeyTyped

    private void txtFinanMontoConadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinanMontoConadiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtFinanMontoConadiKeyTyped

    private void txtFinanMontoConadi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinanMontoConadi2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtFinanMontoConadi2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuarioBDos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cboActividadesPrincipalesProyecto;
    public static javax.swing.JComboBox<String> cboActualmenteDedica;
    public static javax.swing.JComboBox<String> cboAyudasSociales;
    public static javax.swing.JComboBox<String> cboIdentidadCultural;
    public static javax.swing.JComboBox<String> cboIngresoFamiliarPromedio;
    public static javax.swing.JComboBox<String> cboIngresosIndependiente;
    public static javax.swing.JComboBox<String> cboIngresosMedianteProyecto;
    public static javax.swing.JComboBox<String> cboParticipadoPrograma;
    public static javax.swing.JComboBox<String> cboPrestamosCreditos;
    public static javax.swing.JComboBox<String> cboPrincipalMotivacionPostu;
    public static javax.swing.JComboBox<String> cboSubsidioFamiliarEmergencia;
    public static javax.swing.JComboBox<String> cboSubsidioMinimoGarantizado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JTextArea txaActividadPrincipalProyecto;
    public static javax.swing.JTextArea txaAportesPropios;
    public static javax.swing.JTextArea txaExperienciaCapacitacion;
    public static javax.swing.JTextArea txaFinanDetalleProducto;
    public static javax.swing.JTextArea txaFinanDetalleProducto2;
    public static javax.swing.JTextArea txaFormaPromocionarVender;
    public static javax.swing.JTextArea txaProcesoElaboracion;
    public static javax.swing.JTextArea txaTiempoOtorgaraProyecto;
    public static javax.swing.JTextField txtFinanMontoConadi;
    public static javax.swing.JTextField txtFinanMontoConadi2;
    public static javax.swing.JTextField txtGananciaMinimaMensual;
    public static javax.swing.JTextField txtIdentidadCultural;
    public static javax.swing.JTextField txtNombreProyecto;
    public static javax.swing.JTextField txtOtraRelevante;
    // End of variables declaration//GEN-END:variables
}
