/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.BeneProyDAO;
import dao.DesaProyDAO;
import dao.DesarrolloProyDAO;
import dao.DirectosDAO;
import dao.FinanCostoProyDAO;
import dao.IndirectosDAO;
import dao.InfoProyDAO;
import dao.InfoReqProgDAO;
import dao.ProyCostoFinanDAO;
import dao.ProyInfoDAO;
import dao.ResCostoProyDAO;
import entidades.BeneProy;
import entidades.DesaProy;
import entidades.DesarrolloProy;
import entidades.Directos;
import entidades.FinanCostoProy;
import entidades.FinanInstPublPriv;
import entidades.Indirectos;
import entidades.InfoProy;
import entidades.InfoReqProg;
import entidades.ProyCostoFinan;
import entidades.ProyInfo;
import entidades.ResCostoProy;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cactus
 */
public class FormUsuarioBCuatro extends javax.swing.JFrame {

    /**
     * Creates new form FormUsuarioBCuatro
     */
    public FormUsuarioBCuatro() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/logoNewSolutionLogin.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInfraMontoSoliConadi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEquipamientoMontoSoliConadi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        txtAyudaMontoSoliConadi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtResumenAporteSoliConadi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtResumenAportePostulante = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtResumenMontoTotalProyecto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("INFORMACIÓN DEL PROYECTO");

        jLabel2.setText("Nombre del proyecto");

        jLabel3.setText("<html>Indique brevemente cual es el problema principal que<p>afecta a la situación familiar actual.</html>");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("<html>Describa de qué forma solucionará el problema<p>planteado a través del presente proyecto.</html>");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel5.setText("<html>Indique las actividades que considera relevantes<p>para la realización del presente proyecto.</html>");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel6.setText("<html>Indique en qué lugar o recinto será realizada la<p>implementación o equipamiento, según los bienes solicitados<p>a CONADI. </html>");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Infraestructura de la vivienda");

        jLabel9.setText("Monto solicitado a CONADI");

        txtInfraMontoSoliConadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInfraMontoSoliConadiKeyTyped(evt);
            }
        });

        jLabel10.setText("Detalle de productos cotizados");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Equipamiento básico doméstico");

        jLabel12.setText("Monto solicitado a CONADI");

        txtEquipamientoMontoSoliConadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEquipamientoMontoSoliConadiKeyTyped(evt);
            }
        });

        jLabel13.setText("Detalle de productos cotizados");

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Ayuda tecnicas de salud");

        jLabel15.setText("Monto solicitado a CONADI");

        jLabel16.setText("Detalle de productos cotizados");

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane7.setViewportView(jTextArea7);

        txtAyudaMontoSoliConadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAyudaMontoSoliConadiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInfraMontoSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEquipamientoMontoSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAyudaMontoSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtInfraMontoSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEquipamientoMontoSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAyudaMontoSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("FINANCIAMIENTO Y COSTOS DEL PROYECTO");

        jLabel18.setText("Aporte total solicitado a CONADI");

        txtResumenAporteSoliConadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResumenAporteSoliConadiKeyTyped(evt);
            }
        });

        jLabel19.setText("Aporte propio del postulante");

        txtResumenAportePostulante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResumenAportePostulanteKeyTyped(evt);
            }
        });

        jLabel20.setText("Monto total del proyecto");

        txtResumenMontoTotalProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResumenMontoTotalProyectoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResumenAporteSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResumenAportePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResumenMontoTotalProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtResumenAporteSoliConadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtResumenAportePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtResumenMontoTotalProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("RESUMEN DE COSTOS DEL PROYECTO");

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (txtNombreProyecto.getText().trim().isEmpty() || jTextArea1.getText().trim().isEmpty() || jTextArea2.getText().trim().isEmpty()
                || jTextArea3.getText().trim().isEmpty() || jTextArea4.getText().trim().isEmpty() || txtInfraMontoSoliConadi.getText().trim().isEmpty()
                || jTextArea5.getText().trim().isEmpty() || txtEquipamientoMontoSoliConadi.getText().trim().isEmpty() || jTextArea6.getText().trim().isEmpty()
                || txtAyudaMontoSoliConadi.getText().trim().isEmpty() || jTextArea7.getText().trim().isEmpty() || txtResumenAporteSoliConadi.getText().trim().isEmpty()
                || txtResumenAportePostulante.getText().trim().isEmpty() || txtResumenMontoTotalProyecto.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe completar todos los campos para GUARDAR", "ERROR", JOptionPane.WARNING_MESSAGE);

        } else {

            DesarrolloProy dp = new DesarrolloProy();

            dp.setR1(FormUsuarioB.jTextArea1.getText());
            dp.setR2(FormUsuarioB.jTextArea2.getText());
            dp.setR3(FormUsuarioB.jTextArea3.getText());
            dp.setR4(FormUsuarioB.jTextArea4.getText());
            dp.setR5(FormUsuarioB.jTextArea5.getText());
            dp.setR6(FormUsuarioB.jTextArea6.getText());
            dp.setR7(FormUsuarioB.jTextArea7.getText());
            dp.setR8(FormUsuarioB.jTextArea8.getText());
            dp.setR9(FormUsuarioB.jTextArea9.getText());
            dp.setR10(FormUsuarioB.txtDuracionProyMeses.getText());
            dp.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));

            Directos direc = new Directos();

            direc.setHombres(Integer.parseInt(FormUsuarioB.txtDirecHombres.getText()));
            direc.setMujeres(Integer.parseInt(FormUsuarioB.txtDirecMujeres.getText()));
            direc.setTotal(Integer.parseInt(FormUsuarioB.txtDirecTotal.getText()));

            Indirectos indi = new Indirectos();

            indi.setHombres(Integer.parseInt(FormUsuarioB.txtIndiHombres.getText()));
            indi.setMujeres(Integer.parseInt(FormUsuarioB.txtIndiMujeres.getText()));
            indi.setTotal(Integer.parseInt(FormUsuarioB.txtIndiTotal.getText()));
            
            BeneProy beneProy = new BeneProy();
            
            beneProy.setIdPersona(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            InfoReqProg infoReqProg = new InfoReqProg();
            
            infoReqProg.setR1(FormUsuarioBDos.cboIngresoFamiliarPromedio.getSelectedItem().toString());
            infoReqProg.setR2(FormUsuarioBDos.txtGananciaMinimaMensual.getText());
            infoReqProg.setR3(FormUsuarioBDos.cboActualmenteDedica.getSelectedItem().toString());
            infoReqProg.setR4(FormUsuarioBDos.cboPrincipalMotivacionPostu.getSelectedItem().toString());
            infoReqProg.setR5(FormUsuarioBDos.cboIngresosIndependiente.getSelectedItem().toString());
            infoReqProg.setR6(FormUsuarioBDos.cboSubsidioFamiliarEmergencia.getSelectedItem().toString());
            infoReqProg.setR7(FormUsuarioBDos.cboSubsidioMinimoGarantizado.getSelectedItem().toString());
            infoReqProg.setR8(FormUsuarioBDos.cboAyudasSociales.getSelectedItem().toString());
            infoReqProg.setR9(FormUsuarioBDos.cboPrestamosCreditos.getSelectedItem().toString());
            infoReqProg.setR10(FormUsuarioBDos.txtOtraRelevante.getText());
            infoReqProg.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            InfoProy infoProy = new InfoProy();
            
            infoProy.setR1(FormUsuarioBDos.txtNombreProyecto.getText());
            infoProy.setR2(FormUsuarioBDos.txaActividadPrincipalProyecto.getText());
            infoProy.setR3(FormUsuarioBDos.txaTiempoOtorgaraProyecto.getText());
            infoProy.setR4(FormUsuarioBDos.cboIngresosMedianteProyecto.getSelectedItem().toString());
            infoProy.setR5(FormUsuarioBDos.cboActividadesPrincipalesProyecto.getSelectedItem().toString());
            infoProy.setR6(FormUsuarioBDos.txaFormaPromocionarVender.getText());
            infoProy.setR7(FormUsuarioBDos.txaProcesoElaboracion.getText());
            infoProy.setR8(FormUsuarioBDos.txaExperienciaCapacitacion.getText());
            infoProy.setR9(FormUsuarioBDos.cboParticipadoPrograma.getSelectedItem().toString());
            infoProy.setR10(FormUsuarioBDos.txaAportesPropios.getText());
            if(FormUsuarioBDos.cboIdentidadCultural.getSelectedItem() == "Otro"){
                
                infoProy.setR11(FormUsuarioBDos.cboIdentidadCultural.getSelectedItem().toString() + FormUsuarioBDos.txtIdentidadCultural.getText());
                
            }else{
                
                infoProy.setR11(FormUsuarioBDos.cboIdentidadCultural.getSelectedItem().toString());
                
            }
            infoProy.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            FinanCostoProy finanCostoProy = new FinanCostoProy();
            
            
            finanCostoProy.setDetallesProd(FormUsuarioBDos.txaFinanDetalleProducto.getText());
            finanCostoProy.setMontoSoliConadi(Integer.parseInt(FormUsuarioBDos.txtFinanMontoConadi.getText()));
            finanCostoProy.setDetallesProd2(FormUsuarioBDos.txaFinanDetalleProducto2.getText());
            finanCostoProy.setMontoSoliConadi2(Integer.parseInt(FormUsuarioBDos.txtFinanMontoConadi2.getText()));
            finanCostoProy.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            DesaProy desaProy = new DesaProy();
            
            desaProy.setR1(FormUsuarioBTres.jTextArea1.getText());
            desaProy.setR2(FormUsuarioBTres.jTextArea2.getText());
            desaProy.setR3(FormUsuarioBTres.jTextArea3.getText());
            desaProy.setR4(FormUsuarioBTres.jTextArea4.getText());
            desaProy.setR5(FormUsuarioBTres.jTextArea5.getText());
            desaProy.setR6(FormUsuarioBTres.jTextArea6.getText());
            desaProy.setR7(FormUsuarioBTres.jTextArea7.getText());
            desaProy.setR8(FormUsuarioBTres.jTextArea8.getText());
            
            desaProy.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            ProyInfo proyInfo = new ProyInfo();
            
            proyInfo.setR1(txtNombreProyecto.getText());
            proyInfo.setR2(jTextArea1.getText());
            proyInfo.setR3(jTextArea2.getText());
            proyInfo.setR4(jTextArea3.getText());
            proyInfo.setR5(jTextArea4.getText());
            proyInfo.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            ProyCostoFinan proyCostoFinan = new ProyCostoFinan();
            
            proyCostoFinan.setDetalle(jTextArea5.getText());
            proyCostoFinan.setDetalle2(jTextArea6.getText());
            proyCostoFinan.setDetalle3(jTextArea7.getText());
            proyCostoFinan.setMontoSoliConadi(Integer.parseInt(txtAyudaMontoSoliConadi.getText()));
            proyCostoFinan.setMontoSoliConadi2(Integer.parseInt(txtAyudaMontoSoliConadi.getText()));
            proyCostoFinan.setMontoSoliConadi3(Integer.parseInt(txtAyudaMontoSoliConadi.getText()));
            
            proyCostoFinan.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            ResCostoProy resCostoProy = new ResCostoProy();
            
            resCostoProy.setR1(txtResumenAporteSoliConadi.getText());
            resCostoProy.setR2(txtResumenAportePostulante.getText());
            resCostoProy.setR3(txtResumenMontoTotalProyecto.getText());
            
            resCostoProy.setIdPersonaF(Integer.parseInt(FormUsuarioB.txtIdPersonaRefe.getText()));
            
            
            
            DesarrolloProyDAO dpDAO = new DesarrolloProyDAO();
            DirectosDAO dDAO = new DirectosDAO();
            IndirectosDAO iDAO = new IndirectosDAO();
            BeneProyDAO bpDAO = new BeneProyDAO();
            InfoReqProgDAO irpDAO = new InfoReqProgDAO();
            InfoProyDAO ipDAO = new InfoProyDAO();
            FinanCostoProyDAO fcpDAO = new FinanCostoProyDAO();
            DesaProyDAO desaProyDAO = new DesaProyDAO();
            ProyInfoDAO piDAO = new ProyInfoDAO();
            ProyCostoFinanDAO pcfDAO = new ProyCostoFinanDAO();
            ResCostoProyDAO rcpDAO = new ResCostoProyDAO();
            
            
            
            
            try {
                
                if(dpDAO.consultaDatosFichaTecnica(dp)){
                    
                    System.out.println("Desarrollo proyecto insertado!");
                    
                    if(dDAO.consultaDatos(direc, beneProy)){
                        
                        System.out.println("Directos insertado!");
                        
                        if(iDAO.consultaDatos(indi, beneProy)){
                            
                            System.out.println("Indirectos insertado!");
                            
                            if(bpDAO.consultaDatos(beneProy)){
                                
                                System.out.println("Bene proy insertado!");
                                
                                if(irpDAO.insertarRespuesta(infoReqProg)){
                                    
                                    System.out.println("respuestas de Info Requerida Programa insertadas!");
                                    
                                    if(ipDAO.insertarRespuesta(infoProy)){
                                        
                                        System.out.println("respuestas de Info Proyecto insertadas!");
                                        
                                        if(fcpDAO.insertarRespuesta(finanCostoProy)){
                                            
                                            System.out.println("respuestas de Financiamiento y costo de proyecto insertadas!");
                                            
                                            if(desaProyDAO.consultaDatos(dp)){
                                                
                                                System.out.println("respuestas de Desa Proy insertadas!");
                                                
                                                if(piDAO.insertarRespuesta(proyInfo)){
                                                    
                                                    System.out.println("respuestas de Proy Info insertadas!");
                                                    
                                                    if(pcfDAO.consultaDatos(proyCostoFinan)){
                                                        
                                                        System.out.println("respuestas de Proy Costo Finan insertadas!");
                                                        
                                                        if(rcpDAO.insertarRespuesta(resCostoProy)){
                                                            
                                                            System.out.println("respuestas de Res Costo Proy insertadas!");
                                                            
                                                            JOptionPane.showMessageDialog(null, "Respuestas agregadas con exito!!!\n Puede cerrar las demas pestañas");
                                                            
                                                            this.dispose();
                                                            
                                                                    
                                                            
                                                        }
                                                        
                                                    }
                                                    
                                                }
                                                
                                            }
                                            
                                        }
                                        
                                    }
                                    
                                }
                                
                            }
                            
                        }
                        
                    }
                    
                }
                
            } catch (Exception e) {
                
                System.out.println("ERROR: " + e.getMessage());
                
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtInfraMontoSoliConadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInfraMontoSoliConadiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtInfraMontoSoliConadiKeyTyped

    private void txtEquipamientoMontoSoliConadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquipamientoMontoSoliConadiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtEquipamientoMontoSoliConadiKeyTyped

    private void txtAyudaMontoSoliConadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAyudaMontoSoliConadiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtAyudaMontoSoliConadiKeyTyped

    private void txtResumenAporteSoliConadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResumenAporteSoliConadiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtResumenAporteSoliConadiKeyTyped

    private void txtResumenAportePostulanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResumenAportePostulanteKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtResumenAportePostulanteKeyTyped

    private void txtResumenMontoTotalProyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResumenMontoTotalProyectoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");

        }
    }//GEN-LAST:event_txtResumenMontoTotalProyectoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBCuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBCuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBCuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioBCuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuarioBCuatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextArea jTextArea3;
    public static javax.swing.JTextArea jTextArea4;
    public static javax.swing.JTextArea jTextArea5;
    public static javax.swing.JTextArea jTextArea6;
    public static javax.swing.JTextArea jTextArea7;
    public static javax.swing.JTextField txtAyudaMontoSoliConadi;
    public static javax.swing.JTextField txtEquipamientoMontoSoliConadi;
    public static javax.swing.JTextField txtInfraMontoSoliConadi;
    public static javax.swing.JTextField txtNombreProyecto;
    public static javax.swing.JTextField txtResumenAportePostulante;
    public static javax.swing.JTextField txtResumenAporteSoliConadi;
    public static javax.swing.JTextField txtResumenMontoTotalProyecto;
    // End of variables declaration//GEN-END:variables
}
