/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.ComunaDAO;
import dao.DatosPersonaPostulanteDAO;
import dao.DatosProyectoDAO;
import dao.DireccionDAO;
import dao.PersonaDAO;
import dao.ProvinciaDAO;
import dao.RegionDAO;
import entidades.Comuna;
import entidades.DatosPersonaPostulante;
import entidades.DatosProyecto;
import entidades.Direccion;
import entidades.Persona;
import entidades.Provincia;
import entidades.Region;
import entidades.ResumenEje;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cactus
 */
public class FormConsultaA extends javax.swing.JFrame {

    /**
     * Creates new form FormConsultaA
     */
    public FormConsultaA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosPersona = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDireccionPersona = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatosPersonaDos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarPorId = new javax.swing.JTextField();
        btnBuscarPorId = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDatosProyecto = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDireccionProyecto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDatosPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido paterno", "Apellido materno", "Rut", "Telefono", "Telefono 2", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tblDatosPersona);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATOS DE LA PERSONA POSTULANTE");

        tblDireccionPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Direccion", "Comuna", "Provincia", "Region", "Sector"
            }
        ));
        jScrollPane2.setViewportView(tblDireccionPersona);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDatosPersonaDos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pueblo indigena perteneciente", "Fecha postulacion", "N° certificado indigena"
            }
        ));
        jScrollPane3.setViewportView(tblDatosPersonaDos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Buscar por ID:");

        btnBuscarPorId.setText("Buscar");
        btnBuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DATOS DEL PROYECTO");

        tblDatosProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del proyecto", "Nombre propietario inmueble", "Situacion en que propietario facilita postulante"
            }
        ));
        jScrollPane4.setViewportView(tblDatosProyecto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDireccionProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Direccion proyecto", "Sector/Comunidad", "Comuna", "Provincia", "Region"
            }
        ));
        jScrollPane5.setViewportView(tblDireccionProyecto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPorId))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorId))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FormConsultaB abrir = new FormConsultaB();
        abrir.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIdActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            this.listarPorId();

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnBuscarPorIdActionPerformed

    private void listarPorId() throws SQLException {
        if (txtBuscarPorId.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe ingresar un ID", "ERROR", JOptionPane.WARNING_MESSAGE);

        }

        PersonaDAO pDAO = new PersonaDAO();
        DireccionDAO dDAO = new DireccionDAO();
        ComunaDAO cDAO = new ComunaDAO();
        ProvinciaDAO provDAO = new ProvinciaDAO();
        RegionDAO regDAO = new RegionDAO();
        DatosPersonaPostulanteDAO dppDAO = new DatosPersonaPostulanteDAO();
        DatosProyectoDAO dpDAO = new DatosProyectoDAO();

        Persona p = new Persona();
        Direccion d = new Direccion();
        Comuna c = new Comuna();
        Provincia prov = new Provincia();
        Region reg = new Region();
        DatosPersonaPostulante dpp = new DatosPersonaPostulante();
        DatosProyecto dp = new DatosProyecto();
        ResumenEje re = new ResumenEje();

        pDAO.listarPersonaPorId(Integer.parseInt(txtBuscarPorId.getText()), d);
        //dppDAO.listarDatosPersonaPostulantePorId(Integer.parseInt(txtBuscarPorId.getText()));

        try {

            ArrayList<Persona> personas = null;
            ArrayList<Direccion> direcciones = null;
            ArrayList<Comuna> comunas = null;
            ArrayList<Provincia> provincias = null;
            ArrayList<Region> regiones = null;
            ArrayList<DatosPersonaPostulante> datosPersonasPostulantes = null;
            ArrayList<DatosProyecto> datosProyectos = null;
            ArrayList<Direccion> direccionesDatosProyecto = null;
            ArrayList<Comuna> comunasDatosProyecto = null;
            ArrayList<Provincia> provinciasDatosProyecto = null;
            ArrayList<Region> regionesDatosProyecto = null;

            personas = pDAO.listarPersonaPorId(Integer.parseInt(txtBuscarPorId.getText()), d);
            direcciones = dDAO.listarDireccionPorId(d, c);
            comunas = cDAO.listarComunaPorId(prov, c);
            provincias = provDAO.listarProvinciaPorId(prov, reg);
            regiones = regDAO.listarRegionPorId(reg);
            datosPersonasPostulantes = dppDAO.listarDatosPersonaPostulantePorId(Integer.parseInt(txtBuscarPorId.getText()));
            datosProyectos = dpDAO.listarDatosProyectoPorId(d, Integer.parseInt(txtBuscarPorId.getText()));
            direccionesDatosProyecto = dDAO.listarDireccionDatosProyPorId(d, c);
            comunasDatosProyecto = cDAO.listarComunaDatosProyectoPorId(prov, c);
            provinciasDatosProyecto = provDAO.listarProvinciaDatosProyectoPorId(prov, reg);
            regionesDatosProyecto = regDAO.listarRegionDatosProyectoPorId(reg);

            if (personas.size() == 0) {

                JOptionPane.showMessageDialog(null, "No se encontro la persona con el ID ingresado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }

            DefaultTableModel modeloPer = new DefaultTableModel();

            modeloPer.addColumn("Nombre");
            modeloPer.addColumn("Apellido paterno");
            modeloPer.addColumn("Apellido materno");
            modeloPer.addColumn("Rut");
            modeloPer.addColumn("Telefono");
            modeloPer.addColumn("Telefono 2");
            modeloPer.addColumn("Correo");

            DefaultTableModel modeloPer2 = new DefaultTableModel();

            modeloPer2.addColumn("Pueblo indigena perteneciente");
            modeloPer2.addColumn("Fecha postulacion");
            modeloPer2.addColumn("N° certificado indigena");

            DefaultTableModel modeloDireccionPer = new DefaultTableModel();

            modeloDireccionPer.addColumn("Direccion");
            modeloDireccionPer.addColumn("Comuna");
            modeloDireccionPer.addColumn("Provincia");
            modeloDireccionPer.addColumn("Region");
            modeloDireccionPer.addColumn("Sector");

            DefaultTableModel modeloDatosProyecto = new DefaultTableModel();

            modeloDatosProyecto.addColumn("Nombre del proyecto");
            modeloDatosProyecto.addColumn("Nombre propietario inmueble");
            modeloDatosProyecto.addColumn("Situacion en que propietario facilita postulante");

            DefaultTableModel modeloDireccionDatosProyecto = new DefaultTableModel();

            modeloDireccionDatosProyecto.addColumn("Direccion proyecto");
            modeloDireccionDatosProyecto.addColumn("Sector/Comunidad");
            modeloDireccionDatosProyecto.addColumn("Comuna");
            modeloDireccionDatosProyecto.addColumn("Provincia");
            modeloDireccionDatosProyecto.addColumn("Region");

            for (Persona per : personas) {
                String[] fila = new String[7];
                fila[0] = per.getNombres();
                fila[1] = per.getApePat();
                fila[2] = per.getApeMat();
                fila[3] = per.getRut();
                fila[4] = Integer.toString(per.getTelefono());
                fila[6] = per.getCorreo();

                for (DatosPersonaPostulante datpp : datosPersonasPostulantes) {
                    fila[5] = datpp.getTelefonoDos();

                    modeloPer.addRow(fila);

                }

            }

            tblDatosPersona.setModel(modeloPer);

            for (Persona per2 : personas) {
                String[] fila = new String[3];
                fila[0] = per2.getPuebloIndigena();
                fila[1] = per2.getFechaPostulacion();

                for (DatosPersonaPostulante datpp : datosPersonasPostulantes) {
                    fila[2] = Integer.toString(datpp.getNumCertIndigena());

                    modeloPer2.addRow(fila);
                }

            }

            tblDatosPersonaDos.setModel(modeloPer2);

            for (Direccion dir : direcciones) {
                String[] fila = new String[5];
                fila[0] = dir.getDireccion();

                for (Comuna com : comunas) {
                    fila[1] = com.getNombreCom();

                    for (Provincia provi : provincias) {
                        fila[2] = provi.getNombreProv();

                        for (Region regi : regiones) {
                            fila[3] = regi.getNombreReg();

                            for (DatosPersonaPostulante datpp : datosPersonasPostulantes) {
                                fila[4] = datpp.getSector();

                                modeloDireccionPer.addRow(fila);
                            }

                        }
                    }
                }
            }

            tblDireccionPersona.setModel(modeloDireccionPer);

            for (DatosProyecto datosProy : datosProyectos) {
                String[] fila = new String[3];
                fila[0] = datosProy.getNombreProy();
                fila[1] = datosProy.getPropImplProy();
                fila[2] = datosProy.getSitPropInm();

                modeloDatosProyecto.addRow(fila);

            }

            tblDatosProyecto.setModel(modeloDatosProyecto);

            for (Direccion dirDatosProy : direccionesDatosProyecto) {
                String[] fila = new String[5];

                fila[0] = dirDatosProy.getDireccionDatosProyecto();

                for (DatosProyecto datosP : datosProyectos) {
                    fila[1] = datosP.getSectorComunidad();

                    for (Comuna dirCom : comunasDatosProyecto) {
                        fila[2] = dirCom.getNombreComDatosProyecto();
                        
                        for(Provincia dirProv : provinciasDatosProyecto){
                            fila[3] = dirProv.getNombreProvDatosProyecto();
                            
                            for(Region dirReg : regionesDatosProyecto){
                                fila[4] = dirReg.getNombreRegDatosProyecto();
                                
                                modeloDireccionDatosProyecto.addRow(fila);
                                
                            }
                        }
                    }
                }

            }
            
            
            tblDireccionProyecto.setModel(modeloDireccionDatosProyecto);
            

        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblDatosPersona;
    private javax.swing.JTable tblDatosPersonaDos;
    private javax.swing.JTable tblDatosProyecto;
    private javax.swing.JTable tblDireccionPersona;
    private javax.swing.JTable tblDireccionProyecto;
    private javax.swing.JTextField txtBuscarPorId;
    // End of variables declaration//GEN-END:variables
}
